import { defineConfig } from 'vite'
import path from 'path'
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import type { Plugin } from 'vite'
const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

/**
 * Vite plugin: reads docs/{domain}/*.md, extracts ## Status, and generates
 * src/app/data/card-status-map.generated.ts so the roadmap stays in sync
 * with card status changes automatically.
 */
function cardStatusPlugin(): Plugin {
  const docsDir = path.resolve(__dirname, 'docs');
  const outFile = path.resolve(__dirname, 'src/app/data/card-status-map.generated.ts');

  const statusMapping: Record<string, string> = {
    aktiv: 'done',
    'in-arbeit': 'wip',
    geplant: 'planned',
  };

  function generateStatusMap() {
    const entries: [string, string][] = [];

    for (const domain of readdirSync(docsDir, { withFileTypes: true })) {
      if (!domain.isDirectory() || domain.name.startsWith('_')) continue;
      const domainPath = path.join(docsDir, domain.name);
      for (const file of readdirSync(domainPath).filter(f => f.endsWith('.md') && !f.startsWith('_'))) {
        const content = readFileSync(path.join(domainPath, file), 'utf-8');
        const match = content.match(/^## Status\s*\n`([^`]+)`/m);
        if (!match) continue;
        // Extract first status keyword (handles "aktiv (Web/PWA), geplant (Native)" → aktiv)
        const rawStatus = match[1].split(/[,(]/)[0].trim();
        const mapped = statusMapping[rawStatus];
        if (!mapped) continue;
        const cardKey = `${domain.name}/${file.replace(/\.md$/, '')}`;
        entries.push([cardKey, mapped]);
      }
    }

    entries.sort((a, b) => a[0].localeCompare(b[0]));

    const lines = entries.map(([k, v]) => `  "${k}": "${v}",`).join('\n');
    const code = `/**
 * AUTO-GENERATED — Do not edit manually.
 * Generated by vite-plugin-card-status from docs/{domain}/*.md
 *
 * Status-Mapping:
 *   aktiv     → "done"
 *   in-arbeit → "wip"
 *   geplant   → "planned"
 */

import type { RoadmapStatus } from "./roadmap-cards";

const cardStatusMap: Record<string, RoadmapStatus> = {
${lines}
};

export default cardStatusMap;
`;

    // Only write if content changed to avoid unnecessary HMR
    if (existsSync(outFile)) {
      const existing = readFileSync(outFile, 'utf-8');
      if (existing === code) return;
    }
    writeFileSync(outFile, code);
  }

  return {
    name: 'vite-plugin-card-status',
    buildStart() {
      generateStatusMap();
    },
    configureServer(server) {
      server.watcher.add(path.join(docsDir, '**/*.md'));
      server.watcher.on('change', (filePath) => {
        if (filePath.startsWith(docsDir) && filePath.endsWith('.md')) {
          generateStatusMap();
        }
      });
    },
  };
}

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  server: {
    host: '127.0.0.1',
    port: 5173,
    allowedHosts: ['aregoland.de', 'aregoland.com', 'aregoland.eu'],
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    cardStatusPlugin(),
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'icon.svg'],
      manifest: {
        name: 'Aregoland Chat',
        short_name: 'Aregoland',
        description: 'Sichere Kommunikation & Organisation',
        lang: 'de',
        theme_color: '#1D4ED8',
        background_color: '#0f172a',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        icons: [
          {
            src: 'pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024, // 4 MiB — Bundle waechst durch 27 Sprachen
        // Nur App-Shell cachen, keine API-Calls oder WebSocket-Verbindungen
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        navigateFallback: 'index.html',
        runtimeCaching: [
          {
            // Statische Assets mit Cache-First
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|ico|woff|woff2)$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'static-assets',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Tage
              },
            },
          },
        ],
        // Signaling-WebSocket und API-Calls NICHT cachen
        navigateFallbackDenylist: [/^\/ws-signal/, /^\/code/],
      },
      devOptions: {
        enabled: true,
      },
    }),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },
})
