/**
 * AUTO-GENERATED — Do not edit manually.
 * Generated by vite-plugin-card-status from docs/{domain}/*.md
 *
 * Status-Mapping:
 *   aktiv     → "done"
 *   in-arbeit → "wip"
 *   geplant   → "planned"
 */

import type { RoadmapStatus } from "./roadmap-cards";

const cardStatusMap: Record<string, RoadmapStatus> = {
  "account/gdpr-export.card": "done",
  "account/profile": "done",
  "account/qr-code": "done",
  "account/settings": "done",
  "account/subscription": "done",
  "account/support": "wip",
  "calendar/events": "done",
  "calendar/invitations.card": "done",
  "calendar/push-reminders.card": "done",
  "calendar/recurring-events.card": "done",
  "calendar/space-layers.card": "done",
  "calendar/time-blocks.card": "done",
  "calls/call-recording.card": "done",
  "calls/voice-video": "done",
  "child-safety/child-profiles": "done",
  "child-safety/fsk-system": "done",
  "child-safety/parental-controls": "wip",
  "contacts/contact-management": "done",
  "contacts/qr-pairing": "done",
  "documents/file-sharing": "planned",
  "i18n/localization": "done",
  "identity/crypto-keys": "done",
  "identity/registration": "done",
  "identity/subscription": "done",
  "messaging/chat": "done",
  "messaging/media-attachments": "done",
  "messaging/message-storage": "done",
  "native-app/architecture": "planned",
  "native-app/build-pipeline": "done",
  "native-app/pwa-legacy": "done",
  "native-app/web-engine": "planned",
  "p2p-network/e2e-encryption": "done",
  "p2p-network/gossip-protocol": "done",
  "p2p-network/signaling": "done",
  "p2p-network/webrtc": "done",
  "spaces/space-management": "done",
  "spaces/space-sync": "done",
};

export default cardStatusMap;
